export default {
  GET_ALL_INVOICES: 'GET_ALL_INVOICES',
  GET_ONE_INVOICE: 'GET_ONE_INVOICE',
  CREATE_INVOICE: 'CREATE_INVOICE',
  UPDATE_INVOICE: 'UPDATE_INVOICE',
  DELETE_INVOICE: 'DELETE_INVOICE',
  GET_ALL_INVOICES_ERROR: 'GET_ALL_INVOICES_ERROR',
  GET_ONE_INVOICE_ERROR: 'GET_ONE_INVOICE_ERROR',
  CREATE_INVOICE_ERROR: 'CREATE_INVOICE_ERROR',
  UPDATE_INVOICE_ERROR: 'UPDATE_INVOICE_ERROR',
  DELETE_INVOICE_ERROR: 'DELETE_INVOICE_ERROR'
};
